# Generated by Django 4.0.2 on 2022-02-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Meat type')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Meat Type',
                'verbose_name_plural': 'Meat Types',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='meats',
            field=models.ManyToManyField(related_name='meat', to='foodie.MeatType'),
        ),
    ]
