# Generated by Django 4.0.2 on 2022-02-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_alter_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='foodie.foodtype'),
        ),
    ]
