# Generated by Django 4.0.2 on 2022-02-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_meattype_food_meats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='meats',
        ),
        migrations.AddField(
            model_name='meattype',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meat', to='foodie.food'),
            preserve_default=False,
        ),
    ]
