# Generated by Django 4.0.2 on 2022-03-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='food',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='food',
            field=models.ManyToManyField(to='foodie1.Food'),
        ),
    ]
